# Use an official lightweight Python image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy all project files to the container
COPY . /app

# Install dependencies, including missing ones
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install onnx nest_asyncio

# Command to run your application
CMD ["python", "image_classification.py"]
